sudo: required
language: generic
services:
  # we need a copy of docker running
  - docker

before_install:
  # build our image using Dockerfile.dev
  - docker build -t joelclim/docker-react-frontend -f Dockerfile.dev .

scripts:
  # run our test suite
  # - docker run joelclim/docker-react-frontend npm run test -- --coverage
  #
  # CI=true terminates the test suite. You can read up on the CI=true variable here:
  #   https://facebook.github.io/create-react-app/docs/running-tests#linux-macos-bash
  # and environment variables in Docker here:
  #   https://docs.docker.com/engine/reference/run/#env-environment-variables
  - docker run -e CI=true joelclim/docker-react-frontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk

  # The region code can be found by clicking the region 
  #   in the toolbar next to your username in AWS Management Console.
  region: "us-east-1"      
  
  # Elastic Beanstalk Application Name
  app: "docker-react-frontend"

  # Elastic Beanstalk Environment Name (all in lower case)
  env: "dockerreactfrontend-env"        

  # Go to AWS S3 (https://s3.console.aws.amazon.com/s3/)                                                           
  #   Search for the elasticbeanstalk bucket that matches                                                            
  #   the region where you created the application. 
  bucket_name: "elasticbeanstalk-us-east-1-896241416230"
  
  # Elastic Beanstalk Application Name  
  bucket_path: "docker-react-frontend"  

  on:
    branch: master
  
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
